pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 8080

spring:
  datasource.url: jdbc:mysql://43.143.220.18:3306/petmall?useUnicode=true&characterEncoding=utf-8
  datasource.username: root
  datasource.password: wangyp
  datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  redis.host: 43.143.220.18
  redis.port: 6379
  redis.database: 0
  redis.timeout: 1800000
  redis.lettuce.pool.min-idle: 0
  redis.lettuce.pool.max-idle: 5
  redis.lettuce.pool.max-wait: -1
  redis.lettuce.pool.max-active: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

user:
  address.max-count: 20